---

# tasks file for docker_install

- name: Update apt cache and install dependencies
  apt:
    name: 
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Check if Docker is installed
  shell: "which docker"
  register: docker_installed
  ignore_errors: yes
  changed_when: false

- name: Create the directory for Docker's apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: docker_installed.rc != 0

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: docker_installed.rc != 0

- name: Add Docker's apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: docker_installed.rc != 0

- name: Install or Update Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes